# Generated by Django 4.1.2 on 2022-11-24 14:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='on_server_creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='temp_id',
            field=models.CharField(default=datetime.datetime(2022, 11, 24, 14, 21, 14, 551163, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.CharField(max_length=100, unique=True)),
                ('parent_temp_id', models.CharField(max_length=70, null=True)),
                ('child_order', models.IntegerField(default=-1)),
                ('on_server_creation_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=5000, null=True)),
                ('due', models.DateField(null=True)),
                ('priorty', models.IntegerField(default=4)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categories')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
