# Generated by Django 4.1.2 on 2022-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_task_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='on_server_creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
