# Generated by Django 4.1.2 on 2022-12-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_task_on_server_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
